sudo: required
dist: bionic
language: generic
os: linux

jobs:
  include:
  # - php: '7.1'
  #   language: php
  #   env: SWOOLE_VERSION="v4.5.2"
  # - php: '7.2'
  #   language: php
  #   env: SWOOLE_VERSION="v4.5.2"
  # - php: '7.3'
  #   language: php
  #   env: SWOOLE_VERSION="v4.5.2"
  # - php: '7.4'
  #   language: php
  #   env: SWOOLE_VERSION="v4.5.2"
  - os: osx
    language: generic
    osx_image: xcode12
    env: PHP_VERSION=7.4 TEST_SWOOLE_VERSION="fix-atomic-wait" INSTALL_REDIS_EXT=true DISABLE_XDEBUG=false
  # - os: osx
  #   language: generic
  #   osx_image: xcode12
  #   env: PHP_VERSION=7.4 SWOOLE_VERSION="master" INSTALL_REDIS_EXT=true DISABLE_XDEBUG=false
  # - os: osx
  #   language: generic
  #   osx_image: xcode12
  #   env: PHP_VERSION=7.4 SWOOLE_VERSION="v4.5.2" INSTALL_REDIS_EXT=true DISABLE_XDEBUG=false
  # - os: osx
  #   language: generic
  #   osx_image: xcode12
  #   env: PHP_VERSION=7.4 SWOOLE_VERSION="v4.4.19" INSTALL_REDIS_EXT=true DISABLE_XDEBUG=false
  # - php: '7.1'
  #   env: SWOOLE_VERSION="v4.4.19"
  # - php: '7.2'
  #   env: SWOOLE_VERSION="v4.4.19"
  # - php: '7.3'
  #   env: SWOOLE_VERSION="v4.4.19"
  # - php: '7.4'
  #   env: SWOOLE_VERSION="v4.4.19"
  # - php: '7.1'
  #   env: SWOOLE_VERSION="v4.3.6"
  # - php: '7.2'
  #   env: SWOOLE_VERSION="v4.3.6"
  # - php: '7.3'
  #   env: SWOOLE_VERSION="v4.3.6"
  # - php: '7.1'
  #   env: SWOOLE_VERSION="master"
  # - php: '7.2'
  #   env: SWOOLE_VERSION="master"
  # - php: '7.3'
  #   env: SWOOLE_VERSION="master"
  # - php: '7.4'
  #   env: SWOOLE_VERSION="master"
  # - php: 'nightly'
  #   env: SWOOLE_VERSION="master" DISABLE_XDEBUG=false INSTALL_REDIS_EXT=true DOWNLOAD_PHPUNIT=nightly
  allow_failures:
  - env: SWOOLE_VERSION="master"
  - php: nightly

# services:
#   - redis
#   - mysql

addons:
  apt:
    packages:
    - unzip
  # homebrew:
  #   packages:
  #   - redis
  #   - mysql

install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew install php@$PHP_VERSION;
      export PATH="$(brew --prefix php)/bin:$PATH";
      PHP_INI_FILE="/usr/local/etc/php/$PHP_VERSION/php.ini";
      macosSwooleMakeArg="--with-openssl-dir=$(brew --prefix openssl)";
      curl -o composer.phar https://getcomposer.org/composer-stable.phar && chmod +x composer.phar && sudo mv -f composer.phar /usr/local/bin/composer && composer -V;
    fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then
      PHP_INI_FILE="~/.phpenv/versions/$(phpenv version-name)/etc/php.ini";
      dd if=/dev/zero of=swap bs=1024 count=2048000 && chmod 600 swap && sudo mkswap swap && sudo swapon swap;
    fi
  # - if [[ $INSTALL_REDIS_EXT == true ]]; then
  #     wget https://github.com/phpredis/phpredis/archive/develop.zip;
  #     unzip develop.zip;
  #     cd phpredis-develop;
  #     phpize;
  #     ./configure;
  #     make -j && make install;
  #     cd ../;
  #     echo "extension = redis.so" >> $PHP_INI_FILE && php --ri redis;
  #   fi
  - if [[ $TEST_SWOOLE_VERSION ]]; then
      wget https://github.com/Yurunsoft/swoole-src/archive/$TEST_SWOOLE_VERSION.tar.gz -O swoole.tar.gz;
    else
      wget https://github.com/swoole/swoole-src/archive/$SWOOLE_VERSION.tar.gz -O swoole.tar.gz;
    fi
  - mkdir -p swoole && tar -xf swoole.tar.gz -C swoole --strip-components=1 && rm swoole.tar.gz && cd swoole && phpize && ./configure --enable-openssl --enable-http2 --enable-mysqlnd $macosSwooleMakeArg && make -j && make install && cd - && echo "extension = swoole.so" >> $PHP_INI_FILE && php --ri swoole
  - php -v && php -m;
  - if [[ $DOWNLOAD_PHPUNIT != "" ]]; then
      curl -sSfL -o ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-$DOWNLOAD_PHPUNIT.phar && php ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit --version && export TEST_PHPUNIT_PATH=~/.phpenv/versions/$(phpenv version-name)/bin/phpunit;
    fi

before_script:
  # - brew services start redis;
  # - brew services start mysql;
  - if [[ $DISABLE_XDEBUG != false ]]; then
      phpenv config-rm xdebug.ini;
    fi
  # - composer -V && composer update
  # - cd ./tests && composer update && cd ../
  # - sh tests/db/install-db.sh
  # - ./tests/start.sh ./tests/swoole_atomic

script:
  - ./swoole/tests/start.sh ./swoole/tests/swoole_atomic

# after_failure:
#   - php ./.travis/output-server-log.php

env:
  global:
    - MYSQL_SERVER_USERNAME: root
    - MYSQL_SERVER_PASSWORD:
