name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: configure
        run: cmake -Htest -Bbuild/test

      - name: build
        run: cmake --build build/test --config Debug -j4

      - name: test
        run: |
          cd build/test
          ctest --build-config Debug
          cd ../../
          del /S /Q /F .\build
        shell: cmd

      - name: install php x86
        run: .\.github/workflows/bin/install-php7.4-win-x86.ps1

      - name: build and install library with php x86
        run: |
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DWITH_PHP=1 -DPHP_INCLUDE_DIR="%PHP_DEV_PATH%\include" -DPHP_LIB_DIR="%PHP_DEV_PATH%\lib"
          cmake --build build --target install --config Release -j
        shell: cmd

      - name: php x86 test
        run: |
          cd phptest
          composer update
          phpunit
          cd ../
          del /S /Q /F .\build
        shell: cmd

      - name: install php x64
        run: |
          rm c:\php -recurse
          rm "$env:PHP_DEV_PATH" -recurse
          .\.github/workflows/bin/install-php7.4-win-x64.ps1

      - name: build and install library with php x64
        run: |
          rm .\build -recurse
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 -DWITH_PHP=1 -DPHP_INCLUDE_DIR="%PHP_DEV_PATH%\include" -DPHP_LIB_DIR="%PHP_DEV_PATH%\lib"
          cmake --build build --target install --config Release -j
        shell: cmd

      - name: php x64 test
        run: |
          cd phptest
          composer update
          phpunit
